#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2024 Red Bee Media Ltd <https://www.redbeemedia.com/>
#
# SPDX-License-Identifier: MIT

. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit "$1"
