# SPDX-FileCopyrightText: 2024 Red Bee Media Ltd <https://www.redbeemedia.com/>
#
# SPDX-License-Identifier: MIT

name: Build dev site and deploy to version folder on publish

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Install and Build
        run: |
          npm ci
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run webpack and copy style.css
        working-directory: ./apps/demo
        run: |
          echo "PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')" >> $GITHUB_ENV
          npx webpack
      - name: Deploy version folder to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: ./apps/demo/dist
          target-folder: ${{ env.PACKAGE_VERSION }}
          commit-message: Deploy ${{ env.PACKAGE_VERSION }} to GitHub Pages
          clean: false
